name: Upload Nuget Packages

on:
  workflow_run:
    workflows:
      - 'Update Version'
    types:
      - 'completed'

defaults:
  run:
    shell:  |
            pwsh -noninteractive -command "try {{ $ErrorActionPreference='Stop'; . '{0}' }} catch {{ Write-Error ""FAILED: $_""; throw; }} if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) {{ exit $LASTEXITCODE }}"
            
jobs:
  build-and-upload:
    runs-on:  windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      DOTNET_NOLOGO:                true
      DOTNET_CLI_TELEMETRY_OPTOUT:  true

    steps:
      - uses: actions/checkout@v4
        with:
          ref:  ${{ github.ref }}

      - uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version:   6.0.x
          
      - name:   Authenticate with Github NuGet Package Registry
        run:    dotnet nuget add source --username radj307 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/radj307/index.json"

      - name:   Build Package
        run:    |
                dotnet build -c Release


                .\.github\workflows\scripts\SetProperty.ps1 -Path Localization/Localization.csproj                DocumentationFile="../output/`$`(MSBuildProjectName`).xml"
                dotnet pack ./Localization/Localization.csproj --noLogo -c Release -o output --include-symbols

                .\.github\workflows\scripts\SetProperty.ps1 -Path Localization.Json/Localization.Json.csproj      DocumentationFile="../output/`$`(MSBuildProjectName`).xml"
                dotnet pack ./Localization.Json/Localization.Json.csproj --noLogo -c Release -o output --include-symbols

                .\.github\workflows\scripts\SetProperty.ps1 -Path Localization.Yaml/Localization.Yaml.csproj      DocumentationFile="../output/`$`(MSBuildProjectName`).xml"
                dotnet pack ./Localization.Yaml/Localization.Yaml.csproj --noLogo -c Release -o output --include-symbols

                .\.github\workflows\scripts\SetProperty.ps1 -Path Localization.Xml/Localization.Xml.csproj        DocumentationFile="../output/`$`(MSBuildProjectName`).xml"
                dotnet pack ./Localization.Xml/Localization.Xml.csproj --noLogo -c Release -o output --include-symbols

                .\.github\workflows\scripts\SetProperty.ps1 -Path Localization.WPF/Localization.WPF.csproj        DocumentationFile="../output/`$`(MSBuildProjectName`).xml"
                dotnet pack ./Localization.WPF/Localization.WPF.csproj --noLogo -c Release -o output --include-symbols

      - name:   Upload Packages
        run:    >
                cd output;
                foreach ($pkg in $(Get-ChildItem -Filter *.nupkg)) {
                  dotnet nuget push $pkg.Name -k ${{ github.token }} -s "github" --skip-duplicate
                  dotnet nuget push $pkg.Name -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
                }
        
